/**
 * build-icons.js
 * 把 src/icons/*.svg 批量转成 React 组件，并生成 index.ts 统一导出
 */

const fs = require('fs');
const path = require('path');
const { transform } = require('@svgr/core');

const ICONS_DIR = path.resolve(__dirname, '../src/icons');
const OUTPUT_DIR = path.resolve(__dirname, '../src/components');
const INDEX_FILE = path.resolve(__dirname, '../src/index.ts');

// 确保输出目录存在
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// 工具：line_menu_filter → LineMenuFilter
function toComponentName(filename) {
  const name = filename.replace('.svg', '');
  return name
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

// 读取所有 SVG 文件
const svgFiles = fs.readdirSync(ICONS_DIR).filter(f => f.endsWith('.svg'));

if (svgFiles.length === 0) {
  console.log('⚠️  src/icons/ 目录下没有找到 SVG 文件');
  process.exit(0);
}

const exports = [];

console.log(`🔨 开始构建，共 ${svgFiles.length} 个图标...\n`);

svgFiles.forEach(filename => {
  const componentName = toComponentName(filename);
  const svgContent = fs.readFileSync(path.join(ICONS_DIR, filename), 'utf8');

  // SVGR 转换配置
  const jsxCode = transform.sync(
    svgContent,
    {
      plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
      typescript: true,
      // 让 width/height/color 可以通过 props 控制
      svgProps: {
        width: '{size}',
        height: '{size}',
        fill: '{color}',
      },
      template: (variables, { tpl }) => {
        return tpl`
import React from 'react';

interface ${variables.componentName}Props {
  size?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
}

const ${variables.componentName} = ({
  size = 24,
  color = 'currentColor',
  className,
  style,
}: ${variables.componentName}Props): JSX.Element => (
  ${variables.jsx}
);

export default ${variables.componentName};
        `;
      },
    },
    { componentName }
  );

  const outputPath = path.join(OUTPUT_DIR, `${componentName}.tsx`);
  fs.writeFileSync(outputPath, jsxCode, 'utf8');
  exports.push({ componentName, filename: filename.replace('.svg', '') });
  console.log(`  ✅ ${filename} → ${componentName}`);
});

// 生成 index.ts
const indexContent = exports
  .map(({ componentName }) => `export { default as ${componentName} } from './components/${componentName}';`)
  .join('\n');

// 同时导出图标名称列表，方便前端查看所有可用图标
const iconList = exports.map(({ filename }) => `'${filename}'`).join(', ');
const fullIndex = `// Auto-generated by build-icons.js — DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}
// Total icons: ${exports.length}

${indexContent}

// 所有可用图标名称（便于查阅）
export const ICON_NAMES = [${iconList}] as const;
export type IconName = typeof ICON_NAMES[number];
`;

fs.writeFileSync(INDEX_FILE, fullIndex, 'utf8');

console.log(`\n🎉 构建完成！共生成 ${exports.length} 个组件`);
console.log(`📄 入口文件：src/index.ts`);
